package com.adeptj.modularweb.runtime.osgi;

import java.io.IOException;
import java.io.InputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.adeptj.modularweb.runtime.common.CommonUtils;

/**
 * ErrorHandlerServlet that handles the error generated by the system i.e. 401, 403, 404, 500 etc.
 *
 * @author Rakesh.Kumar, AdeptJ
 */
public class ErrorHandlerServlet extends HttpServlet {

	private static final long serialVersionUID = -3339904764769823449L;

	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		InputStream resource = getClass().getResourceAsStream(String.format("/error/views/%s.html", this.getStatusCode(req)));
		if (resource == null) {
			resp.getWriter().write(CommonUtils.toString(getClass().getResourceAsStream("/error/views/404.html")));
		} else {
			resp.getWriter().write(CommonUtils.toString(resource));
		}
	}

	private String getStatusCode(HttpServletRequest req) {
		String requestURI = req.getRequestURI();
		return requestURI.substring(requestURI.lastIndexOf('/') + 1);
	}
}